### ISSUE TITLE
Provide given and family name during Apple native sign in

### ISSUE THREAD

**Issue by dippa-1** [supabase-community/flutter-auth-ui#105]
# Feature request

## Is your feature request related to a problem? Please describe.

When signing up with Apple natively, the name is not propagated to supabase and not returned by the `_nativeAppleSignIn()` method.

However, Apple has strict rules: when a user signs up natively with their name, the app must not ask for their name again, because the user has already given us their name.

## Describe the solution you'd like

Provide a callback during `_nativeAppleSignIn()` that takes
```dart
    final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      nonce: hashedNonce,
    );

    // My addition here:
    onAppleFullNameReceived(credential.givenName, credential.familyName);

    // continue with supa auth
```

## Describe alternatives you've considered

Best way would be to fix supabase so they already include the names in the raw metadata like with Google OAuth. But I was not able to dig into it.

## Additional context

I have created a solution that works for me in a branch, will create a PR.

**Comment by dshukertjr** [comment]
When a user signs in using Apple for the first time for the app, Apple will provide the full name and email address if the user approves it. The full name and email address will be available in the raw user metadata the same way as Google login, and you can use triggers to store them in any table that you would like. 

If you are not seeing the full name and email address after completing the Apple sign in, it means that the user has signed-in on the same app before.

**Comment by dippa-1** [comment]
I don't see this happening, even in production. I even added analytics logs to my app whenever someone signs up using apple, and the metadata have never been there. There are also open issues on supabase. The only thing that is working is this workaround that others have proposed and that I am using now and have started in my fork.

**Comment by dshukertjr** [comment]
Could you link the issues that you have found discussing this topic? If it's an existing bug, we should fix it the proper way. The Supabase auth server should be storing that information on the user's metadata.

**Comment by dippa-1** [comment]
Here the references:
- same behavior in the js library: https://github.com/supabase/supabase-js/issues/899
- older issue where you answered as well: https://github.com/supabase/supabase-flutter/issues/545

However, I've seen this comment from you:
> @takuya-ohmuro Currently, Supabase does request for email and full name scope when performing Apple sign in. You can retrieve the full name like this:
> 
> ```dart
> final response = await supabase.auth.signInWithApple();
> print(response.user?.userMetadata?['full_name']);
> ```

But the method `signInWithApple` does not exist anymore. Instead, the native apple sign in is used and then the `signInWithIdToken`.
I don't even know why it should work, because the native apple sign in returns the full name in the credentials, but these credentials are only used for the identity token and the name is thrown away. Maybe I don't see the hidden magic here. Also, I don't know how the old function worked, maybe you know more.

Another option that I have not tested yet is at the `_nativeAppleSignIn()` call, the return type is ignored. Per haps that auth response holds the metadata and we would then have to call `supabase.auth.updateUser` with that metadata, but would still not be a pretty way to handle this.

**Comment by KhaleelSH** [comment]
In my flutter code I fixed it by adding the following code after `signInWithIdToken`:
```
    await supabase.auth.updateUser(
      UserAttributes(
        data: {
          'given_name': credential.givenName,
          'family_name': credential.familyName,
        },
      ),
    );
```

**Comment by rochajulian** [comment]
any solution to this? still happening
