### ISSUE TITLE
Enable redirect for apps not using named routes

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/flutter-auth-ui#11]
Currently, the widgets are configured to support apps that are using named routes. I would like to be able to use regular navigation as well using this library.

**Comment by FatumaA** [comment]
Could you elaborate on this? do you mean nav 2 or regular non named routes

**Comment by dshukertjr** [comment]
Yeah, so I personally do not use named routes in my app, and instead use MaterialPageRoute whenever I need to go to another page. Kind of like this:

```dart
Navigator.of(context).push(MaterialPageRoute(builder: (context) => NextPage()));
```

**Comment by dshukertjr** [comment]
This issue is fixed now that we have `onSuccess` and `onError` callbacks
