### ISSUE TITLE
Add docs for this under auth helpers?

### ISSUE THREAD

**Issue by FatumaA** [supabase-community/flutter-auth-ui#16]
ReadMe should show how to initialise the project when using this library. 
You don't need the supabase_flutter dependency directly if only using the auth ui lib

**Comment by pschuegr** [comment]
Agreed.  The documentation is pretty thin, I hope they continue working on this.

**Comment by FatumaA** [comment]
It will def keep being worked on 🙂

**Comment by FatumaA** [comment]
@dshukertjr What do you think of adding docs for this under auth helpers?

**Comment by dshukertjr** [comment]
@FatumaA Thanks for coming back to this. Adding docs under auth helpers sounds great. 

Let me wrap up https://github.com/supabase-community/flutter-auth-ui/pull/46 real quick and then let's add the docs under auth helpers!
