### ISSUE TITLE
Resume on App Startup 

### ISSUE THREAD

**Issue by HankG** [supabase-community/flutter-auth-ui#20]
Under the pre-1.0 API resume on app launch happened by calling into the SupabaseAuthState.recoverSupabaseSession(). A version of that method still exists on SupabaseAuth but it is now private and only accessed through SupabaseAuth.didChangeAppLifecycleState with a "resumed" AppLifecycleState value. I can't see where that is being called. In the Supabase Auth UI project I created a method which calls `SupabaseAuth.instance.didChangeAppLifecycleState(AppLifecycleState.resumed)`. I can get it to resume the session but there are a couple of problems. First, the _recoverSupabaseSession() is async but didChangeAppLifecycleState is not so there is no way to await for the return or to know what the return value was. Second, it feels like this is supposed to be initiated somewhere else but I can't determine where. My workaround right now is to call this right after init, add a button to a splash screen to go into the real part of the app, and then only click that button once I see that the session has been restored in the output. That is all obviously not ideal.

Is there a plan to have this reload exposed elsewhere in a way we can wait for it at our app level or expose the recover method itself for direct initiation?

**Comment by dshukertjr** [comment]
@HankG 
>Secondarily I can't figure out the best idiomatic place to put a Supabase.instance.client.auth.onAuthStateChange to track the state changes that used to get picked up by the SupabaseAuthState class. Handling it in the context of the MyApp causes an error Unhandled Exception: Navigator operation requested with a context that does not include a Navigator. since of course the MaterialApp is what has the navigation. What's the best place for it?

How may want to navigate depending on the auth state differs case to case, I'd say. If you want to do something like redirect the user to a login page if they are not logged in, and redirect the user to the home page if they are logged in, you can just create a preloader page where every user is initially taken to, and then get `currentUser` and redirect the user accordingly.

**Comment by HankG** [comment]
@dshukertjr That one flow is easy. I was more thinking having something so that if the state changed to being signed out at some point from anywhere you are redirected to the login page. I guess worst case one could put that in every screen's code.

**Comment by dshukertjr** [comment]
@HankG 
As long as you have one active `onAuthStateChange` listener in your Widget tree, it should be fine. No need to include it in every screen. Just include it in whatever your "root" page it!

**Comment by HankG** [comment]
> @HankG As long as you have one active `onAuthStateChange` listener in your Widget tree, it should be fine. No need to include it in every screen. Just include it in whatever your "root" page it!

Right but it can't be a screen that gets swapped in and out of the widget tree, which is a common paradigm at least some point through an app lifecycle where it's bouncing around screens etc. In a modification of the standard example it reads like below (still needs the actual async version of SuperbaseAuthUI's init method to be there though for this to work correctly on startup.:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: '.env');
  await SupabaseAuthUi().initSupabase(
      dotenv.env['SUPABASE_URL']!, dotenv.env['SUPABASE_ANON_KEY']!);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final appNavigatorKey = GlobalKey<NavigatorState>();
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Supabase.instance.client.auth.onAuthStateChange((event, session) {
      switch (event) {
        case AuthChangeEvent.signedOut:
        case AuthChangeEvent.userDeleted:
          Navigator.of(appNavigatorKey.currentContext!)
              .pushNamedAndRemoveUntil('/sign_in', (route) => false);
          break;
        default:
          break;
      }
    });

    return MaterialApp(
      navigatorKey: appNavigatorKey,
      title: "Auth UI Demo",
      initialRoute: '/home',
      routes: {
        '/': (_) => const SplashPage(),
        '/home': (_) => Home(),
        '/sign_in': (_) => const SignIn(),
        '/sign_up': (_) => const SignUp(),
      },
      onUnknownRoute: (RouteSettings settings) {
        return MaterialPageRoute(
            settings: settings,
            builder: (context) => Scaffold(
                body:
                    Center(child: Text('Route not found: ${settings.name}'))));
      },
    );
  }
}
```

**Comment by HankG** [comment]
FYI submitted a PR on the init method needing to be async. https://github.com/supabase-community/flutter-auth-ui/pull/21

**Comment by dshukertjr** [comment]
@HankG Thanks for the PR. I will take a look at it right now. 

In a typical Flutter application, you should have a `Home` widget, where it sits at the root of the Navigator, unless you are replacing your routes all the time, so you should be able to do something like this:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  await SupabaseAuthUi().initSupabase('URL', 'ANON_KEY');
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      initialRoute: '/loading',
      routes: {
        '/': (context) => const Home(),
        '/sign_in': (context) => const SignIn(),
        '/loading': (context) => const Preload(),
      },
    );
  }
}

class Preload extends StatefulWidget {
  const Preload({Key? key}) : super(key: key);

  @override
  State<Preload> createState() => _PreloadState();
}

class _PreloadState extends State<Preload> {
  @override
  void initState() {
    _redirect();
    super.initState();
  }

  Future<void> _redirect() async {
    try {
      final session = await SupabaseAuth.instance.initialSession;
      if (session == null) {
        Navigator.of(context).pushReplacementNamed('/sign_in');
      } else {
        Navigator.of(context).pushReplacementNamed('/home');
      }
    } catch (error) {
      Navigator.of(context).pushReplacementNamed('/sign_in');
    }
  }

  @override
  Widget build(BuildContext context) {
    return const Center(child: CircularProgressIndicator());
  }
}

class SignIn extends StatelessWidget {
  const SignIn({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SupaEmailAuth(
        authAction: AuthAction.signIn,
        redirectUrl: '/',
      ),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    Supabase.instance.client.auth.onAuthStateChange((event, session) {
      switch (event) {
        case AuthChangeEvent.signedOut:
        case AuthChangeEvent.userDeleted:
          Navigator.of(context)
              .pushNamedAndRemoveUntil('/sign_in', (route) => false);
          break;
        default:
          break;
      }
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold();
  }
}
```

You might have other routes come on top of `Home` widget, but as long as you don't replace `Home` widget, the user will be taken back to `SignIn` page once they sign out. Does this answer your question?

**Comment by dshukertjr** [comment]
I am going to close this issue, but if you still are facing some issues, please feel to reopen it!
