### ISSUE TITLE
Better example of deep link

### ISSUE THREAD

**Issue by dhurbhat** [supabase-community/flutter-auth-ui#53]
# Improve documentation

## [Link](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#setup-deep-links) 

Add a link to the page which needs improvement (if relevant)

## The whole deep link to app is very, very confusing to me... I don't know what a "redirect_url" to an Android or iOS app would be to configure "redirect url".  The use of site_url is clear enough but what if I want the user to come back to the mobile app after signup and email confirmation?  See: https://github.com/orgs/supabase/discussions/5947#discussioncomment-6158307

Is the documentation missing? Or is it confusing? Why is it confusing?

## Show me a proper sequence diagram; show me step by step examples.  Tell me why should I add `localhost:3000` in site_url but `io.supabase.flutterquickstart://login-callback` - where did the `io.supabase.flutterquickstart` come from?  Is the the name of the flutter project?  Is it the name of the Supabase project? what is `login-callback`?  Is it a page?  Or is it a route in flutter?

I've suggested a sequence diagram - it would convey a whole lot.

If there is additional context that's necessary - e.g., "You'll need to learn Android deep links and how they work - go here" etc. - would take a **huge** amount of guess work.

**PLEASE**

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by FatumaA** [comment]
Hi,
Apologies for the very late response.
I believe this two links offer more guidance on redirects and deep links:
- https://supabase.com/docs/guides/auth/concepts/redirect-urls
- https://supabase.com/docs/guides/auth/native-mobile-deep-linking
