### ISSUE TITLE
Dependency version solving failed

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [supabase-community/flutter-auth-ui#68]
# Bug report

## Describe the bug

When I want to add supabase_auth_ui v0.4.0+1 to my flutter project, I always get a dependency version solving failed when I run `flutter pub get`. Here is my Flutter and dart version:

```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (3 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

## To Reproduce

1. Create a new flutter project
2. Add these dependencies

```
 cupertino_icons: ^1.0.2
  supabase_flutter: ^2.1.0
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  slideable: ^0.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_signin_button: ^2.0.0
  banner_carousel: ^1.2.1
  multi_dropdown: ^2.1.3
  chips_choice: ^3.0.1
  font_awesome_flutter: ^9.2.0
  matcher: ^0.12.16
  material_color_utilities: ^0.5.0
  meta: ^1.10.0
  path: ^1.8.3
  test_api: ^0.6.1
  web: ^0.3.0
  web_socket_channel: ^2.4.0
  supabase_auth_ui: ^0.4.0+1
  ```
3. Run flutter pub get

## Expected behavior

I expect the behavior successfully added the supabase_auth_ui package to my project.

## System information

- OS: macOS Sonoma v14.2.1
- Flutter: 3.16.5 channel stable
- Dart: 3.2.3

## Additional context

Command output from `flutter pub get`
```
Because supabase_auth_ui >=0.4.0 depends on font_awesome_flutter ^10.6.0 and sushi_app depends on font_awesome_flutter ^9.2.0,
  supabase_auth_ui >=0.4.0 is forbidden.
So, because sushi_app depends on supabase_auth_ui ^0.4.0+1, version solving failed.
```

**Comment by dshukertjr** [comment]
@AlphaByte-RedTeam You do have the answer in the error message you are getting. You can upgrade `font_awesome_flutter` to `^10.6.0`, and it will work just fine 😁

**Comment by AlphaByte-RedTeam** [comment]
> @AlphaByte-RedTeam You do have the answer in the error message you are getting. You can upgrade `font_awesome_flutter` to `^10.6.0`, and it will work just fine 😁

yeah I notice it. Upgrade the version and everything will be resolved. But I also got another dependency version issue. And I don't know why.

**Comment by dshukertjr** [comment]
@AlphaByte-RedTeam 
>But I also got another dependency version issue

Could you share more details about it? Are you getting any error messages?
