### ISSUE TITLE
Add authScreenLaunchMode 

### ISSUE THREAD

**Issue by r-paxst** [supabase-community/flutter-auth-ui#84]
# Feature request: 
Add authScreenLaunchMode to https://pub.dev/packages/supabase_auth_ui package

## Is your feature request related to a problem? Please describe.
Yes. Current experience when using social logins for Google, Facebook, and Apple is an internal browser to login and then to display redirect. However, the onSuccess function and session data is not provided until the user redirects back to the app. With the current experience users have to pull up on the internal browser before they can see the iOS redirect link (assume similar experience with Android) which triggers onSuccess and session data to be sent to app. However, the user then also needs to click done to finish and be navigated to the post login app page.

This requires high cognitive load on users to understand they need to pull down on internal browser, click redirect link which is not intuitive because they are already in the app, and then click done to finish logging in. 

Instead if authScreenLaunchMode option was available I could assign LaunchMode.externalApplication and the redirect would automatically prompt user to return to app after logging in. Have tested and this solves the issue above.

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like
Add authScreenLaunchMode as a parameter to SupaSocialsAuth Widget and allow user to assign LaunchMode.externalApplication type.

## Describe alternatives you've considered
Manually create own socials login UI and use supabase.auth.signInWithOauth which has authScreenLaunchMode: LaunchMode.externalApplication capability.

**Comment by FatumaA** [comment]
Hi,
Would you be willing to send in a PR for this since you've tested out a working solution already? 🙂
