### ISSUE TITLE
AuthRetryableFetchException (AuthException(message: AuthRetryableFetchError, statusCode: null))

### ISSUE THREAD

**Issue by Justincyz** [supabase-community/flutter-auth-ui#86]
# Bug report

## Describe the bug

I am trying to use the email as an authentication tool and based on this repo. But I keep getting the error "Exception has occurred. AuthRetryableFetchException (AuthException(message: AuthRetryableFetchError, statusCode: null))" and I could not figure out why for a few days. Before this, using Google email as a sign-up option works fine on my project. Moreover, every time I launch my project/do sign-up authentication, I can see the number of requests increase on DataBase and Auth modules on the Supabase website. Now I am confused what happened. 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. download this repo,
2. open on Visual Studio, 
3. replace Superbase_url and Superbase_anonKey with my project identification. 
4. do email sign-up

## Expected behavior

able to sign-up by using email address

## Screenshots

<img width="776" alt="截屏2024-04-18 15 31 41" src="https://github.com/supabase-community/flutter-auth-ui/assets/30378016/213d356b-20ed-403a-86d7-9f8733f8d8e2">
<img width="791" alt="截屏2024-04-18 15 33 35" src="https://github.com/supabase-community/flutter-auth-ui/assets/30378016/7226d7f3-170e-4de7-a5fa-48e57974b766">

## System information

- OS: macOS
- Version of supabase-js: latest

**Comment by henry2man** [comment]
I'm not sure if this could be related, but I had some of these errors today using a local Supabase environment. 

A combo of `supabase stop -> supabase start` CLI commands fixed the issue, please don't tell me why 🤷🏻‍♂️

**Comment by devmalcrysis** [comment]
I just started an old proyect and had the same exact error. I went to the supabase console and found out the proyect was paused. Once I fixed that the app started working again.

Maybe check that.

**Comment by dshukertjr** [comment]
Yeah, this most likely means that the app cannot connect to the Supabase instance. Check if the internet connection is fine, and the instance is live.
