### ISSUE TITLE
FR: Override social provider names in SupaSocialsAuth ("Azure" --> "Microsoft (Azure)" for example)

### ISSUE THREAD

**Issue by henry2man** [supabase-community/flutter-auth-ui#87]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to customize the shown names in `SupaSocialsAuth` widget. Precisely, I want to change the label "Azure" with "Microsoft (Azure)". Why? Simple: Normal people won't correlate Azure with Microsoft as developers does.

## Describe the solution you'd like

Have extra localization attributes in `SupaSocialsAuthLocalization` for provider names

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by dshukertjr** [comment]
Great suggestion! I have opened a PR for it. Would love to hear what you think.

**Comment by henry2man** [comment]
> Great suggestion! I have opened a PR for it. Would love to hear what you think.

LGTM 👍🏻
